env:
  browser: true
  es6: true
  node: true

extends:
  - '@ridedott/eslint-config'
  - 'plugin:react/recommended'

overrides:
  - files: ./src/**/*spec.ts
    rules:
      '@typescript-eslint/no-magic-numbers': 'off'

parserOptions:
  ecmaVersion: 10
  project: tsconfig.json
  sourceType: module

rules:
  immutable/no-mutation: 'off'
  immutable/no-this: 'off'
  unicorn/filename-case:
    - error
    - case: kebabCase

  # Annoying
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/typedef': off
  '@typescript-eslint/explicit-module-boundary-types': off
  sort-keys: off
